testMode = false
autoSwitchLanguage = true
autoDownloadVMTranslationPack = false
translationPackSource = "GITEE"
checkModPackTranslationUpdate = true
i18nUpdateModCheck = true
vaultPatcherCheck = false