name: Paratranz To GitHub

on:
  schedule:
    # 每天北京时间早晚10点左右自动运行
    - cron: "0 1,13 * * *"
  workflow_dispatch:

jobs:
  paratranz-to-gitHub:
    name: Paratranz To GitHub
    environment: PARATRANZ_ENV
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      packages: write
    env:
      API_TOKEN: ${{ secrets.API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECT_ID: ${{ vars.ID }}
    outputs:
      changed: ${{ steps.commit.outputs.changed }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3"

      - name: Install dependencies
        run: |
          pip install requests ftb_snbt_lib

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "VM[BOT]"

      - name: Sync translations from Paratranz
        run: python .github/scripts/para2github.py

      - name: Run FTB Color Checker Script
        run: python .github/scripts/check_ftb_colors.py ./CNPack
        continue-on-error: true

      - name: Check if error_report.html was generated
        id: check_report
        run: |
          if [ -f error_report.html ]; then
            echo "error_report_exists=true" >> $GITHUB_ENV
          else
            echo "error_report_exists=false" >> $GITHUB_ENV
          fi
        
      - name: Commit and Push changes
        id: commit
        run: |
          # 检查工作区，如果没有任何更改，则提前退出
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes detected from Paratranz. Nothing to commit."
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          git rm --cached --ignore-unmatch error_report.html

          git add .
          git commit -m '从Paratranz同步翻译'
          git push

          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Upload Error Report Artifact
        if: ${{ env.error_report_exists == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: error-report
          path: error_report.html

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: paratranz-to-gitHub
    if: needs.paratranz-to-gitHub.outputs.changed == 'true'
    environment: PARATRANZ_ENV
    permissions: 
      contents: write

    steps:
      - name: Checkout code for Release
        uses: actions/checkout@v5
        with:
          ref: 'main'

      - name: Download Error Report Artifact (if exists)
        id: download_error
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: error-report
          path: ./

      - name: Get current datetime for tag
        id: datetime
        run: echo "datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Zip CNPack folder
        run: zip -r "VM-CNPack-${{ env.datetime }}.zip" ./CNPack

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: "test-${{ env.datetime }}"
          name: "测试版构建 ${{ env.datetime }}"
          body: |
            自动生成的最新汉化补丁

            ${{ steps.download_error.outcome == 'success' && '⚠ 注意：本次同步检测到 FTB 任务文本颜色可能存在错误，详见 release 附带的 error_report.html。' || '✔ 未发现异常颜色，FTB任务颜色字符检查通过。' }}
          artifacts: |
            VM-CNPack-${{ env.datetime }}.zip
            error_report.html
          draft: false
          prerelease: true
